# GitHub: https://github.com/MetaCubeX/mihomo [12k]
# docker: https://hub.docker.com/r/metacubex/mihomo/tags
# 参考: https://github.com/Izumiko/docker-mihomo

version: "3"

services:
  # Clash
  clash:
    image: mihomo
    container_name: mihomo
    volumes:
      # - ../../mnt/clash/config:/root/.config/clash
      - ../../mnt/mihomo/config:/root/.config/mihomo
    ports:
      - ${CLASH_PORT}:7890/tcp
      - ${CLASH_PORT}:7890/udp
      - ${CLASH_EXTERNAL_PORT}:9090
    restart: always
    networks:
      - shared_network

  # Clash Dashboard
  clash-dashboard:
    image: hitian/clash-dashboard  # centralx/clash-dashboard 无了, 只好替换
    container_name: clash-dashboard
    ports:
      - "${CLASH_DASHBOARD_PORT}:80"
    restart: always
    networks:
      - shared_network

# # Networks
# networks:
#   shared_network:
#     driver: bridge
#     name: clash
networks:
  shared_network:
    external: true