---
# https://docs.linuxserver.io/images/docker-calibre-web
# https://hub.docker.com/r/linuxserver/calibre-web
# 注意这个可能要等比较久
version: "2.1"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      # 注意, 若为非root启动docker, 则需要将 $UID, $GID 替换为对应的组; 会造成config文件own为 root
      - PUID=1000
      - PGID=1000
      # - TZ=Europe/London
      - TZ Asia/Shanghai
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      # - /home/lighthouse/data/calibre/book:/config
      # - /home/lighthouse/data/calibre/book:/books
      - /home/syc/docker/calibre-web/books:/books
      - /home/syc/docker/calibre-web/config:/config
    ports:
      - 8083:8083
    restart: unless-stopped