# 一个比较精简的教程 ⭐️: https://blog.csdn.net/weixin_42274846/article/details/127952296
# === Grafana ===
# web: https://grafana.com
# 可视化配置
#   Node Exporter Full: https://grafana.com/grafana/dashboards/1860-node-exporter-full/
#   Docker and system monitoring: https://grafana.com/grafana/dashboards/893-main/
#   Docker and OS metrics ( cadvisor, node_exporter ): https://grafana.com/grafana/dashboards/10566-docker-and-os-metrics/


version: "3.8"
services:

# docker run -d -p 9100:9100 \
#   -v "/proc:/host/proc:ro" \
#   -v "/sys:/host/sys:ro" \
#   -v "/:/rootfs:ro" \
#   prom/node-exporter
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - '${NODE_EXPORTER_PORT}:9100'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - shared_network

# https://github.com/google/cadvisor
# docker run -v /:/rootfs:ro -v /var/run:/var/run:rw -v /sys:/sys:ro -v /var/lib/docker/:/var/lib/docker:ro -v /dev/disk:/dev/disk:ro -p 8082:8080 -d --name=cadvisor google/cadvisor:latest
  cadvisor:
    # image:  google/cadvisor:latest            # NOTE: DEPRECATED https://hub.docker.com/r/google/cadvisor/
    # image: gcr.io/cadvisor/cadvisor:latest    # DEBUG: 无法访问 https://qinyang.wang/china-mirror-proxy 
    image: gcr.nju.edu.cn/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - '${CADVISOR_PORT}:8080'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - shared_network


# https://hub.docker.com/r/prom/prometheus
# docker run --name prometheus -d -p 127.0.0.1:9090:9090 prom/prometheus
# /Users/qiao/opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  \
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - '${PROMETHEUS_PORT}:9090'
    volumes:
      - ../../mnt/prometheus/data:/prometheus
      - ../../mnt/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - shared_network


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
     - '${GRAFANA_PORT}:3000'
    volumes:
      - ../../mnt/grafana/data:/var/lib/grafana
      # - ../../mnt/grafana/config/grafana.ini:/etc/grafana/grafana.ini
      # - ../../mnt/grafana/config/ldap.toml:/etc/grafana/ldap.toml
      - ../../mnt/grafana/config:/etc/grafana
    networks:
      - shared_network


networks:
  shared_network:
    external: true
