# WARNING: 停用中!!! 目前是机器上的 ShellCrash
# https://weibo.com/ttarticle/p/show?id=2309404876225410630195#_loginLayer_1715485490926
# docker: https://hub.docker.com/r/dreamacro/clash
# 配置项: https://clash.wiki/configuration/configuration-reference.html

version: "3"

services:
  # Clash
  clash:
    image: dreamacro/clash
    container_name: clash
    volumes:
      - ../../mnt/clash/config:/root/.config/clash
    ports:
      - ${CLASH_PORT}:7890/tcp
      - ${CLASH_PORT}:7890/udp
      - ${CLASH_EXTERNAL_PORT}:9090
    restart: always
    networks:
      - shared_network

  # Clash Dashboard
  clash-dashboard:
    image: hitian/clash-dashboard  # centralx/clash-dashboard 无了, 只好替换
    container_name: clash-dashboard
    ports:
      - "${CLASH_DASHBOARD_PORT}:80"
    restart: always
    networks:
      - shared_network

# Networks
networks:
  shared_network:
    external: true