# =========================================================
# 启动: docker-compose up -d
# 重启: docker-compose restart    # 在不指定name的时候才能使用!
# 停止: docker-compose down
# see https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/docker-compose.yml

version: '3'
services:
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    volumes:
      - ../../mnt/nginx/data/html:/usr/share/nginx/html
      - ../../mnt/hexo/data/public:/usr/share/nginx/hexo
      - ../../mnt/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ../../mnt/nginx/config/conf.d:/etc/nginx/conf.d
      - ../../mnt/nginx/config/sites-enabled:/etc/nginx/sites-enabled
      - ../../mnt/nginx/logs:/var/log/nginx
    ports:
      - "80:80"
    # environment:
    #   - NGINX_HOST=foobar.com
    #   - NGINX_PORT=80
    
    # 自定义一个网络!! 
    networks:
      - shared_network
networks:
  shared_network:
    external: true