# =========================================================
# 启动: docker-compose up -d
# 重启: docker-compose restart    # 在不指定name的时候才能使用!
# 停止: docker-compose down
# 访问: http://127.0.0.1:9001/buckets

version: '3'
services:
  minio:
    image: quay.io/minio/minio
    # name: minio
    ports:
      - "9303:9000"
      - "9304:9001"
    volumes:
      - ../../mnt/minio/data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    restart: unless-stopped
    command: server /data --console-address ":9001"



