# https://www.home-assistant.io/installation/linux/#docker-compose
version: '3.8'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      # - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    # network_mode: host
    ports:
      # Also required for macOS since the network directive in docker-compose does not work
      - "8123:8123"
      - "21064:21064"
      - "21065:21065"
      - "21066:21066"
